{"name": "test_failed", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@allure.feature(\"Тест failed\")\n    def test_failed():\n>   \tassert False\nE    assert False\n\ntest_registration.py:25: AssertionError"}, "start": 1756626432169, "stop": 1756626432171, "uuid": "5390b4ec-d8f1-4edc-bf27-685877990a09", "historyId": "4fff94c619f87b8cfbd805772a40a41b", "testCaseId": "4fff94c619f87b8cfbd805772a40a41b", "fullName": "test_registration#test_failed", "labels": [{"name": "feature", "value": "Тест failed"}, {"name": "suite", "value": "test_registration"}, {"name": "host", "value": "DESKTOP-N08PBDF"}, {"name": "thread", "value": "30468-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_registration"}], "titlePath": ["test_registration.py"]}